[package]
name = "extism-test"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "plugin/"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extism = "0.5.2"
serde = "1.0.189"
